export interface SpecMasterRecord {
  id: string;
  spec_key: string;
  spec_full: string;
  steel_grade: string | null;
  smys_mpa: number | null;
  uts_mpa: number | null;
  elongation_pct: number | null;
  hardness: string | null;
  straightness: string | null;
  color_spec: string | null;
  rm_color: string | null;
  whf_temp: string | null;
  induction_temp: string | null;
  sizing_outlet_temp: string | null;
  ht_cycle: string | null;
  ht_condition: string | null;
  ndt: string | null;
  holding_time_sec: number | null;
  coating: string | null;
  end_condition: string | null;
  bundling: string | null;
  end_cap: string | null;
  is_min_wall: boolean;
  is_active: boolean;
  created_at?: string;
  updated_at?: string;
}

export const DEFAULT_SPEC_MASTER_RECORDS: SpecMasterRecord[] = [
  {
    id: 'seed-a106',
    spec_key: 'A106',
    spec_full: 'ASTM A106 Gr B (IBR)',
    steel_grade: 'SAE 1018 / 15C8 RS-03',
    smys_mpa: 240,
    uts_mpa: 415,
    elongation_pct: 21,
    hardness: '79 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE',
    rm_color: 'YELLOW + WHITE',
    whf_temp: '1220° C (+/- 40° C)',
    induction_temp: '850 °C - 880° C',
    sizing_outlet_temp: '880° C TO 900° C',
    ht_cycle: 'NA',
    ht_condition: 'AS ROLLED / HFS',
    ndt: 'UT',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH',
    end_condition: 'BEVEL END (30°-35°) ROOT FACE (0.8 - 2.4MM)',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: false,
    is_active: true,
  },
  {
    id: 'seed-a53',
    spec_key: 'A53',
    spec_full: 'ASTM A53 Gr B (Type S)',
    steel_grade: 'IS 2062 / SAE 1020',
    smys_mpa: 240,
    uts_mpa: 415,
    elongation_pct: 21,
    hardness: '82 HRB MAX',
    straightness: '1:1000',
    color_spec: 'BLUE',
    rm_color: 'BLUE + WHITE',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'NA',
    ht_condition: 'AS ROLLED',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH',
    end_condition: 'BEVEL END (30°-35°)',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: false,
    is_active: true,
  },
  {
    id: 'seed-a312-304l',
    spec_key: 'A312_304L',
    spec_full: 'ASTM A312 TP304L',
    steel_grade: 'AISI 304L / UNS S30403',
    smys_mpa: 170,
    uts_mpa: 485,
    elongation_pct: 35,
    hardness: '90 HRB MAX',
    straightness: '1:1000',
    color_spec: 'YELLOW',
    rm_color: 'YELLOW',
    whf_temp: '1180° C - 1220° C',
    induction_temp: '1040 °C - 1080° C',
    sizing_outlet_temp: '1050° C',
    ht_cycle: 'SOLUTION ANNEALING',
    ht_condition: '1040°C - 1100°C WATER QUENCH',
    ndt: 'ECT + UT',
    holding_time_sec: 5,
    coating: 'PASSIVATED / PICKLED',
    end_condition: 'PLAIN END / BEVEL END',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC CAP',
    is_min_wall: false,
    is_active: true,
  },
  {
    id: 'seed-a312-316l',
    spec_key: 'A312_316L',
    spec_full: 'ASTM A312 TP316L',
    steel_grade: 'AISI 316L / UNS S31603',
    smys_mpa: 170,
    uts_mpa: 485,
    elongation_pct: 30,
    hardness: '90 HRB MAX',
    straightness: '1:1000',
    color_spec: 'GREEN',
    rm_color: 'GREEN + WHITE',
    whf_temp: '1180° C - 1220° C',
    induction_temp: '1050 °C - 1100° C',
    sizing_outlet_temp: '1050° C',
    ht_cycle: 'SOLUTION ANNEALING',
    ht_condition: '1050°C - 1120°C RAPID WATER QUENCH',
    ndt: 'ECT + UT',
    holding_time_sec: 5,
    coating: 'PASSIVATED / PICKLED',
    end_condition: 'PLAIN END / BEVEL END',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC CAP',
    is_min_wall: false,
    is_active: true,
  },
  {
    id: 'seed-a213-t11',
    spec_key: 'A213_T11',
    spec_full: 'ASTM A213 T11 (IBR)',
    steel_grade: '1.25Cr - 0.5Mo Alloy',
    smys_mpa: 205,
    uts_mpa: 415,
    elongation_pct: 30,
    hardness: '85 HRB MAX',
    straightness: '1:1000',
    color_spec: 'ORANGE',
    rm_color: 'ORANGE + WHITE',
    whf_temp: '1200° C - 1250° C',
    induction_temp: '900 °C - 950° C',
    sizing_outlet_temp: '900° C',
    ht_cycle: 'ISOTHERMAL ANNEALING / N&T',
    ht_condition: 'NORMALIZE 900-940°C, TEMPER 650-700°C',
    ndt: 'UT + MT',
    holding_time_sec: 5,
    coating: 'RUST PREVENTIVE OIL',
    end_condition: 'BEVEL END (30°-35°)',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC CAP',
    is_min_wall: true,
    is_active: true,
  },
  {
    id: 'seed-a335-p22',
    spec_key: 'A335_P22',
    spec_full: 'ASTM A335 P22 (IBR)',
    steel_grade: '2.25Cr - 1Mo Alloy',
    smys_mpa: 205,
    uts_mpa: 415,
    elongation_pct: 30,
    hardness: '85 HRB MAX',
    straightness: '1:1000',
    color_spec: 'RED + WHITE',
    rm_color: 'RED + WHITE',
    whf_temp: '1220° C - 1260° C',
    induction_temp: '920 °C - 960° C',
    sizing_outlet_temp: '920° C',
    ht_cycle: 'NORMALIZED & TEMPERED',
    ht_condition: 'NORMALIZE 920-960°C, TEMPER 680-720°C',
    ndt: 'UT + MT',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'BEVEL END (30°-35°)',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC CAP',
    is_min_wall: true,
    is_active: true,
  },
  {
    id: 'seed-a210',
    spec_key: 'A210',
    spec_full: 'ASME SA210 Gr A-1 (IBR) / ASTM A210 Gr A-1',
    steel_grade: 'MEDIUM-CARBON STEEL (SA210 Gr.A1)',
    smys_mpa: 255,
    uts_mpa: 415,
    elongation_pct: 30,
    hardness: '79 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + BLUE',
    rm_color: 'YELLOW + BLUE',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'SUB-CRITICAL ANNEALED / NORMALIZED',
    ht_condition: 'SUB-CRITICAL ANNEAL (650°C - 700°C) / NORMALIZED',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: true,
    is_active: true,
  },
  {
    id: 'seed-a210-c',
    spec_key: 'A210_C',
    spec_full: 'ASME SA210 Gr C (IBR) / ASTM A210 Gr C',
    steel_grade: 'MEDIUM-CARBON STEEL (SA210 Gr.C)',
    smys_mpa: 275,
    uts_mpa: 485,
    elongation_pct: 30,
    hardness: '89 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + RED',
    rm_color: 'YELLOW + RED',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'SUB-CRITICAL ANNEALED / NORMALIZED',
    ht_condition: 'SUB-CRITICAL ANNEAL (650°C - 700°C) / NORMALIZED',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: true,
    is_active: true,
  },
  {
    id: 'seed-bs3059-320',
    spec_key: 'BS3059_320',
    spec_full: 'BS 3059 Part 1 Gr 320 (IBR)',
    steel_grade: 'CARBON STEEL (BS 3059 Gr.320)',
    smys_mpa: 195,
    uts_mpa: 320,
    elongation_pct: 25,
    hardness: '75 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + YELLOW',
    rm_color: 'YELLOW + WHITE',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'NORMALIZED / SUB-CRITICAL ANNEALED',
    ht_condition: 'NORMALIZED 880-920°C / SUB-CRITICAL ANNEAL 650-700°C',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: true,
    is_active: true,
  },
  {
    id: 'seed-bs3059-360',
    spec_key: 'BS3059_360',
    spec_full: 'BS 3059 Part 2 Gr 360 (IBR)',
    steel_grade: 'CARBON STEEL (BS 3059 Gr.360)',
    smys_mpa: 215,
    uts_mpa: 360,
    elongation_pct: 24,
    hardness: '77 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + BLUE',
    rm_color: 'YELLOW + BLUE',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'NORMALIZED / SUB-CRITICAL ANNEALED',
    ht_condition: 'NORMALIZED 880-920°C / SUB-CRITICAL ANNEAL 650-700°C',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: true,
    is_active: true,
  },
  {
    id: 'seed-bs3059-440',
    spec_key: 'BS3059_440',
    spec_full: 'BS 3059 Part 2 Gr 440 (IBR)',
    steel_grade: 'CARBON STEEL (BS 3059 Gr.440)',
    smys_mpa: 255,
    uts_mpa: 440,
    elongation_pct: 21,
    hardness: '82 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + GREEN',
    rm_color: 'YELLOW + GREEN',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'NORMALIZED / SUB-CRITICAL ANNEALED',
    ht_condition: 'NORMALIZED 880-920°C / SUB-CRITICAL ANNEAL 650-700°C',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: true,
    is_active: true,
  },
  {
    id: 'seed-bs3059-620',
    spec_key: 'BS3059_620',
    spec_full: 'BS 3059 Part 2 Gr 620 / 622 (IBR)',
    steel_grade: 'ALLOY STEEL (BS 3059 Gr.620/622)',
    smys_mpa: 310,
    uts_mpa: 580,
    elongation_pct: 18,
    hardness: '88 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + ORANGE',
    rm_color: 'YELLOW + ORANGE',
    whf_temp: '1200° C - 1250° C',
    induction_temp: '900 °C - 950° C',
    sizing_outlet_temp: '900° C',
    ht_cycle: 'NORMALIZED & TEMPERED',
    ht_condition: 'NORMALIZE 930-970°C, TEMPER 650-720°C',
    ndt: 'UT + MT',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: true,
    is_active: true,
  },
];
