// scripts/seed_pending_order_specs.cjs
const SUPABASE_URL = "https://dzhvbftmuwfyuaarsxtk.supabase.co/rest/v1";
const KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6aHZiZnRtdXdmeXVhYXJzeHRrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NzUwOTYzNywiZXhwIjoyMTAzMDg1NjM3fQ.jtkcZxBOmgEEHvBzGIHYdPpzJf2zA5xfdJZ6XuDSmds";

const headers = {
  apikey: KEY,
  Authorization: `Bearer ${KEY}`,
  "Content-Type": "application/json",
  Prefer: "resolution=merge-duplicates"
};

const SPECIFICATIONS = [
  {
    spec_key: 'A106',
    spec_full: 'ASTM A106 Gr B (IBR) / ASME SA106 Gr B',
    steel_grade: 'Carbon Steel (SAE 1018 / 15C8 RS-03)',
    smys_mpa: 240,
    uts_mpa: 415,
    elongation_pct: 21,
    hardness: '79 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE',
    rm_color: 'YELLOW + WHITE',
    whf_temp: '1220° C (+/- 40° C)',
    induction_temp: '850 °C - 880° C',
    sizing_outlet_temp: '880° C TO 900° C',
    ht_cycle: 'NA / AS ROLLED',
    ht_condition: 'AS ROLLED / HFS (OR NORMALIZED / STRESS RELIEVED FOR CDS)',
    ndt: 'UT',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH',
    end_condition: 'BEVEL END (30°-35°) ROOT FACE (0.8 - 2.4MM)',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: false,
    is_active: true
  },
  {
    spec_key: 'SA106_C',
    spec_full: 'ASME SA106 Gr C (IBR) / ASTM A106 Gr C',
    steel_grade: 'High-Strength Carbon Steel (SA106 Gr.C)',
    smys_mpa: 275,
    uts_mpa: 485,
    elongation_pct: 20,
    hardness: '85 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + BROWN',
    rm_color: 'YELLOW + BROWN',
    whf_temp: '1220° C (+/- 40° C)',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'NORMALIZED',
    ht_condition: 'NORMALIZE 900°C - 940°C AIR COOL',
    ndt: 'UT',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH',
    end_condition: 'BEVEL END (30°-35°)',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: false,
    is_active: true
  },
  {
    spec_key: 'A53',
    spec_full: 'ASTM A53 Gr B (Type S)',
    steel_grade: 'IS 2062 / SAE 1020',
    smys_mpa: 240,
    uts_mpa: 415,
    elongation_pct: 21,
    hardness: '82 HRB MAX',
    straightness: '1:1000',
    color_spec: 'BLUE',
    rm_color: 'BLUE + WHITE',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'NA',
    ht_condition: 'AS ROLLED',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH',
    end_condition: 'BEVEL END (30°-35°)',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: false,
    is_active: true
  },
  {
    spec_key: 'A210',
    spec_full: 'ASME SA210 Gr A-1 (IBR) / ASTM A210 Gr A-1',
    steel_grade: 'Medium-Carbon Steel (SA210 Gr.A1)',
    smys_mpa: 255,
    uts_mpa: 415,
    elongation_pct: 30,
    hardness: '79 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + BLUE',
    rm_color: 'YELLOW + BLUE',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'SUB-CRITICAL ANNEALED / NORMALIZED',
    ht_condition: 'SUB-CRITICAL ANNEAL (650°C - 700°C) / NORMALIZED',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: true,
    is_active: true
  },
  {
    spec_key: 'A210_C',
    spec_full: 'ASME SA210 Gr C (IBR) / ASTM A210 Gr C',
    steel_grade: 'Medium-Carbon Steel (SA210 Gr.C)',
    smys_mpa: 275,
    uts_mpa: 485,
    elongation_pct: 30,
    hardness: '89 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + RED',
    rm_color: 'YELLOW + RED',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'SUB-CRITICAL ANNEALED / NORMALIZED',
    ht_condition: 'SUB-CRITICAL ANNEAL (650°C - 700°C) / NORMALIZED',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: true,
    is_active: true
  },
  {
    spec_key: 'SA192',
    spec_full: 'ASME SA 192 (IBR) / ASTM A192',
    steel_grade: 'Seamless Carbon Steel Boiler Tubes (SA192)',
    smys_mpa: 180,
    uts_mpa: 325,
    elongation_pct: 35,
    hardness: '77 HRB MAX',
    straightness: '1:1000',
    color_spec: 'YELLOW + BLUE',
    rm_color: 'YELLOW + BLUE',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'SUB-CRITICAL ANNEALED / NORMALIZED',
    ht_condition: 'SUB-CRITICAL ANNEAL (650°C - 700°C) AFTER COLD FINISHING',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'RUST PREVENTIVE OIL / CLEAR VARNISH',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: true,
    is_active: true
  },
  {
    spec_key: 'SA179',
    spec_full: 'ASME SA 179 (IBR) / ASTM A179',
    steel_grade: 'Seamless Cold-Drawn Low-Carbon Steel (SA179)',
    smys_mpa: 180,
    uts_mpa: 325,
    elongation_pct: 35,
    hardness: '72 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + BLACK',
    rm_color: 'YELLOW + BLACK',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'SUB-CRITICAL ANNEALED / NORMALIZED',
    ht_condition: 'HEAT TREATED AFTER FINAL COLD DRAW PASS AT 650°C MIN',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'RUST PREVENTIVE OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: true,
    is_active: true
  },
  {
    spec_key: 'A213_T11',
    spec_full: 'ASME SA213 Gr.T11 (IBR) / ASTM A213 T11',
    steel_grade: '1.25Cr - 0.5Mo Alloy Steel (SA213 Gr.T11)',
    smys_mpa: 205,
    uts_mpa: 415,
    elongation_pct: 30,
    hardness: '85 HRB MAX',
    straightness: '1:1000',
    color_spec: 'ORANGE',
    rm_color: 'ORANGE + WHITE',
    whf_temp: '1200° C - 1250° C',
    induction_temp: '900 °C - 950° C',
    sizing_outlet_temp: '900° C',
    ht_cycle: 'ISOTHERMAL ANNEALED / NORMALIZED & TEMPERED',
    ht_condition: 'NORMALIZE 900-940°C, TEMPER 650-700°C',
    ndt: 'UT + MT',
    holding_time_sec: 5,
    coating: 'RUST PREVENTIVE OIL',
    end_condition: 'PLAIN END / BEVEL END (30°-35°)',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC CAP',
    is_min_wall: true,
    is_active: true
  },
  {
    spec_key: 'A213_T12',
    spec_full: 'ASME SA213 GR.T12 (IBR) / ASTM A213 T12',
    steel_grade: '1Cr - 0.5Mo Alloy Steel (SA213 Gr.T12)',
    smys_mpa: 220,
    uts_mpa: 415,
    elongation_pct: 30,
    hardness: '85 HRB MAX',
    straightness: '1:1000',
    color_spec: 'ORANGE + GREEN',
    rm_color: 'ORANGE + GREEN',
    whf_temp: '1200° C - 1250° C',
    induction_temp: '900 °C - 950° C',
    sizing_outlet_temp: '900° C',
    ht_cycle: 'NORMALIZED & TEMPERED',
    ht_condition: 'NORMALIZE 900-940°C, TEMPER 650-710°C',
    ndt: 'UT + MT',
    holding_time_sec: 5,
    coating: 'RUST PREVENTIVE OIL',
    end_condition: 'PLAIN END / BEVEL END (30°-35°)',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC CAP',
    is_min_wall: true,
    is_active: true
  },
  {
    spec_key: 'A213_T22',
    spec_full: 'ASME SA213 GR.T22 (IBR) / ASTM A213 T22',
    steel_grade: '2.25Cr - 1Mo Alloy Steel (SA213 Gr.T22)',
    smys_mpa: 205,
    uts_mpa: 415,
    elongation_pct: 30,
    hardness: '85 HRB MAX',
    straightness: '1:1000',
    color_spec: 'RED + WHITE',
    rm_color: 'RED + WHITE',
    whf_temp: '1220° C - 1260° C',
    induction_temp: '920 °C - 960° C',
    sizing_outlet_temp: '920° C',
    ht_cycle: 'NORMALIZED & TEMPERED',
    ht_condition: 'NORMALIZE 920-960°C, TEMPER 680-720°C',
    ndt: 'UT + MT',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'PLAIN END / BEVEL END (30°-35°)',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC CAP',
    is_min_wall: true,
    is_active: true
  },
  {
    spec_key: 'A335_P11',
    spec_full: 'ASME A335 GR P11 (IBR) / ASME SA335 GR P11',
    steel_grade: '1.25Cr - 0.5Mo Alloy Steel (P11 Pipe)',
    smys_mpa: 205,
    uts_mpa: 415,
    elongation_pct: 30,
    hardness: '85 HRB MAX',
    straightness: '1:1000',
    color_spec: 'ORANGE',
    rm_color: 'ORANGE + WHITE',
    whf_temp: '1200° C - 1250° C',
    induction_temp: '900 °C - 950° C',
    sizing_outlet_temp: '900° C',
    ht_cycle: 'NORMALIZED & TEMPERED',
    ht_condition: 'NORMALIZE 900-940°C, TEMPER 650-700°C',
    ndt: 'UT + MT',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'BEVEL END (30°-35°)',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC CAP',
    is_min_wall: false,
    is_active: true
  },
  {
    spec_key: 'A335_P22',
    spec_full: 'ASME SA335 GR P22 (IBR) / ASME A335 GR P22',
    steel_grade: '2.25Cr - 1Mo Alloy Steel (P22 Pipe)',
    smys_mpa: 205,
    uts_mpa: 415,
    elongation_pct: 30,
    hardness: '85 HRB MAX',
    straightness: '1:1000',
    color_spec: 'RED + WHITE',
    rm_color: 'RED + WHITE',
    whf_temp: '1220° C - 1260° C',
    induction_temp: '920 °C - 960° C',
    sizing_outlet_temp: '920° C',
    ht_cycle: 'NORMALIZED & TEMPERED',
    ht_condition: 'NORMALIZE 920-960°C, TEMPER 680-720°C',
    ndt: 'UT + MT',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'BEVEL END (30°-35°)',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC CAP',
    is_min_wall: false,
    is_active: true
  },
  {
    spec_key: 'BS3059_320',
    spec_full: 'BS 3059-P1 GR320 (IBR)',
    steel_grade: 'Carbon Steel (BS 3059 Gr.320)',
    smys_mpa: 195,
    uts_mpa: 320,
    elongation_pct: 25,
    hardness: '75 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + YELLOW',
    rm_color: 'YELLOW + WHITE',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'NORMALIZED / SUB-CRITICAL ANNEALED',
    ht_condition: 'NORMALIZED 880-920°C / SUB-CRITICAL ANNEAL 650-700°C',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: false,
    is_active: true
  },
  {
    spec_key: 'BS3059_360',
    spec_full: 'BS 3059-P2 GR360 (IBR)',
    steel_grade: 'Carbon Steel (BS 3059 Gr.360)',
    smys_mpa: 215,
    uts_mpa: 360,
    elongation_pct: 24,
    hardness: '77 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + BLUE',
    rm_color: 'YELLOW + BLUE',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'NORMALIZED / SUB-CRITICAL ANNEALED',
    ht_condition: 'NORMALIZED 880-920°C / SUB-CRITICAL ANNEAL 650-700°C',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: false,
    is_active: true
  },
  {
    spec_key: 'BS3059_440',
    spec_full: 'BS 3059 Part 2 Gr 440 (IBR)',
    steel_grade: 'Carbon Steel (BS 3059 Gr.440)',
    smys_mpa: 255,
    uts_mpa: 440,
    elongation_pct: 21,
    hardness: '82 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + GREEN',
    rm_color: 'YELLOW + GREEN',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'NORMALIZED / SUB-CRITICAL ANNEALED',
    ht_condition: 'NORMALIZED 880-920°C / SUB-CRITICAL ANNEAL 650-700°C',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: false,
    is_active: true
  },
  {
    spec_key: 'BS3059_620',
    spec_full: 'BS 3059 Part 2 Gr 620 / 622 (IBR)',
    steel_grade: 'Alloy Steel (BS 3059 Gr.620/622)',
    smys_mpa: 310,
    uts_mpa: 580,
    elongation_pct: 18,
    hardness: '88 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + ORANGE',
    rm_color: 'YELLOW + ORANGE',
    whf_temp: '1200° C - 1250° C',
    induction_temp: '900 °C - 950° C',
    sizing_outlet_temp: '900° C',
    ht_cycle: 'NORMALIZED & TEMPERED',
    ht_condition: 'NORMALIZE 930-970°C, TEMPER 650-720°C',
    ndt: 'UT + MT',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: false,
    is_active: true
  },
  {
    spec_key: 'ST35_8',
    spec_full: 'DIN 17175 St 35.8 (IBR) / ST 35.8',
    steel_grade: 'Heat-Resistant Carbon Steel (St 35.8 III)',
    smys_mpa: 235,
    uts_mpa: 420,
    elongation_pct: 25,
    hardness: '78 HRB MAX',
    straightness: '1:1000',
    color_spec: 'WHITE + BROWN',
    rm_color: 'YELLOW + BROWN',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '860 °C - 890° C',
    sizing_outlet_temp: '880° C TO 920° C',
    ht_cycle: 'NORMALIZED',
    ht_condition: 'NORMALIZE 890°C - 930°C AIR COOL',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'BLACK VARNISH / RUST OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: false,
    is_active: true
  },
  {
    spec_key: 'DIN2391_ST52',
    spec_full: 'DIN 2391 ST 52 / EN 10305-1 E355',
    steel_grade: 'High-Yield Precision Carbon Steel (St 52 / E355)',
    smys_mpa: 355,
    uts_mpa: 520,
    elongation_pct: 22,
    hardness: '85 HRB MAX',
    straightness: '1:1000',
    color_spec: 'BLUE + WHITE',
    rm_color: 'BLUE + WHITE',
    whf_temp: '1200° C - 1240° C',
    induction_temp: '880 °C - 920° C',
    sizing_outlet_temp: '890° C TO 930° C',
    ht_cycle: 'STRESS RELIEVED / NORMALIZED (+SR / +N)',
    ht_condition: 'STRESS RELIEF 550-600°C OR NORMALIZE 890-930°C',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'LIGHT RUST PREVENTIVE OIL',
    end_condition: 'PLAIN END / SQUARE CUT DEBURRED',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: false,
    is_active: true
  },
  {
    spec_key: 'MS_900DP',
    spec_full: 'MS 900DP Dual Phase High Strength Tubing',
    steel_grade: 'Dual Phase High-Strength Steel (DP 900)',
    smys_mpa: 650,
    uts_mpa: 900,
    elongation_pct: 14,
    hardness: '95 HRB MAX',
    straightness: '1:1000',
    color_spec: 'VIOLET',
    rm_color: 'VIOLET + WHITE',
    whf_temp: '1200° C - 1250° C',
    induction_temp: '900 °C - 950° C',
    sizing_outlet_temp: '920° C',
    ht_cycle: 'CONTROLLED INTERCRITICAL ANNEAL + QUENCH',
    ht_condition: 'INTERCRITICAL DUAL-PHASE HEAT TREATMENT (780-820°C WATER QUENCH)',
    ndt: 'UT + FLUX LEAKAGE',
    holding_time_sec: 5,
    coating: 'RUST PREVENTIVE OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: false,
    is_active: true
  },
  {
    spec_key: 'SAE_1010',
    spec_full: 'SAE 1010 Mechanical Tubing (ASTM A519)',
    steel_grade: 'Low Carbon Mechanical Steel (SAE 1010)',
    smys_mpa: 205,
    uts_mpa: 365,
    elongation_pct: 20,
    hardness: '70 HRB MAX',
    straightness: '1:1000',
    color_spec: 'GREEN + WHITE',
    rm_color: 'GREEN + WHITE',
    whf_temp: '1180° C - 1220° C',
    induction_temp: '850 °C - 880° C',
    sizing_outlet_temp: '870° C TO 900° C',
    ht_cycle: 'ANNEALED / STRESS RELIEVED (+A / +SR)',
    ht_condition: 'SUB-CRITICAL ANNEAL 620-680°C',
    ndt: 'UT / ET',
    holding_time_sec: 5,
    coating: 'LIGHT RUST PREVENTIVE OIL',
    end_condition: 'PLAIN END / SQUARE CUT',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC PROTECTOR',
    is_min_wall: false,
    is_active: true
  },
  {
    spec_key: 'A312_304L',
    spec_full: 'ASTM A312 TP304L',
    steel_grade: 'AISI 304L / UNS S30403',
    smys_mpa: 170,
    uts_mpa: 485,
    elongation_pct: 35,
    hardness: '90 HRB MAX',
    straightness: '1:1000',
    color_spec: 'YELLOW',
    rm_color: 'YELLOW',
    whf_temp: '1180° C - 1220° C',
    induction_temp: '1040 °C - 1080° C',
    sizing_outlet_temp: '1050° C',
    ht_cycle: 'SOLUTION ANNEALING',
    ht_condition: '1040°C - 1100°C WATER QUENCH',
    ndt: 'ECT + UT',
    holding_time_sec: 5,
    coating: 'PASSIVATED / PICKLED',
    end_condition: 'PLAIN END / BEVEL END',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC CAP',
    is_min_wall: false,
    is_active: true
  },
  {
    spec_key: 'A312_316L',
    spec_full: 'ASTM A312 TP316L',
    steel_grade: 'AISI 316L / UNS S31603',
    smys_mpa: 170,
    uts_mpa: 485,
    elongation_pct: 30,
    hardness: '90 HRB MAX',
    straightness: '1:1000',
    color_spec: 'GREEN',
    rm_color: 'GREEN + WHITE',
    whf_temp: '1180° C - 1220° C',
    induction_temp: '1050 °C - 1100° C',
    sizing_outlet_temp: '1050° C',
    ht_cycle: 'SOLUTION ANNEALING',
    ht_condition: '1050°C - 1120°C RAPID WATER QUENCH',
    ndt: 'ECT + UT',
    holding_time_sec: 5,
    coating: 'PASSIVATED / PICKLED',
    end_condition: 'PLAIN END / BEVEL END',
    bundling: 'HEXAGONAL',
    end_cap: 'PLASTIC CAP',
    is_min_wall: false,
    is_active: true
  }
];

async function seed() {
  console.log(`Seeding ${SPECIFICATIONS.length} specifications into material_spec_master...`);
  
  for (const s of SPECIFICATIONS) {
    const res = await fetch(`${SUPABASE_URL}/material_spec_master?on_conflict=spec_key`, {
      method: "POST",
      headers,
      body: JSON.stringify(s)
    });
    
    if (res.ok || res.status === 201) {
      console.log(`[OK] ${s.spec_key} -> ${s.spec_full}`);
    } else {
      const err = await res.text();
      console.error(`[FAIL] ${s.spec_key}:`, res.status, err);
    }
  }
  
  // Verify final count
  const verifyRes = await fetch(`${SUPABASE_URL}/material_spec_master?select=id,spec_key,spec_full,is_min_wall`, {
    headers: { apikey: KEY, Authorization: `Bearer ${KEY}` }
  });
  const allSpecs = await verifyRes.json();
  console.log(`\nSuccessfully populated material_spec_master! Total rows: ${allSpecs.length}`);
}

seed();
